# Generated by Django 3.0.3 on 2020-07-18 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Contact Number', max_length=22)),
                ('pickup', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('ouruser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ourusers', to='booking.OurUser')),
            ],
        ),
    ]
