# Generated by Django 3.0.3 on 2020-08-29 18:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='ouruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.OurUser'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='phone',
            field=models.CharField(max_length=22),
        ),
    ]
